### PR TITLE
chore: minor fixes & tweaks

### LINKED ISSUE #235: token details header styling issue
the spacing in the header does not look consistent

image

### PR DESCRIPTION
**Pull request by alanrsoares**
changes:

- optimize `searchGMP` params for tx status queries
-  move `useGetTransactionsStatusesOnDestinationChainsQuery` searchGMP call to trpc
- set min row height for `TokenDetailsSection` closes #235 
- `packages/api`: update searchGMP types to accept array of contract names
- upgrade dependencies

### CODE REVIEW

File: apps/maestro/src/server/routers/gmp/getTransactionStatusOnDestinationChains.ts [hunk 1]
```diff
@@ -31,7 +59,7 @@ export const getTransactionStatusOnDestinationChains = publicProcedure
             [call.returnValues.destinationChain.toLowerCase()]: {
               status,
               txHash: call.transactionHash,
-              logIndex: call._logIndex,
+              logIndex: call.logIndex ?? call._logIndex ?? 0,
```
Comment (canhtrinh) [inline apps/maestro/src/server/routers/gmp/getTransactionStatusOnDestinationChains.ts:62]: :(, but I get it

**Review by canhtrinh — APPROVED** [review]
