### PR TITLE
chore: add report bug button

### LINKED ISSUE #277: add HELP widget and make it more prominent
Add this [link](https://axelar.zendesk.com/hc/en-us/requests/new) to the footer

### PR DESCRIPTION
**Pull request by npty**
# Description

Closes #277 [AXE-3647](https://axelarnetwork.atlassian.net/browse/AXE-3647)

Adds "Report Bug" button at the footer
image

[AXE-3647]: https://axelarnetwork.atlassian.net/browse/AXE-3647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: apps/maestro/src/ui/layouts/MainLayout/MainMenu.tsx [hunk 1]
```diff
@@ -226,6 +226,12 @@ export const BOTTOM_MENU_ITEMS: Menuitem[] = [
       </Content.Wrapper>
     ),
   },
+  {
+    kind: "link",
+    label: "Report Bug",
```
Comment (canhtrinh) [inline apps/maestro/src/ui/layouts/MainLayout/MainMenu.tsx:231]:
```suggestion
    label: "Report Feedback",
```

**Review by canhtrinh — APPROVED** [review]
